name: Run CoinGecko Scanner Every 5 Minutes

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run scan
        run: python scan_cg.py

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/cg_gainers.csv
          git commit -m "Update cg_gainers.csv" || echo "No changes to commit"
          git push
